### ISSUE TITLE
Modify LLVM tracer to make Fault Injection 

### ISSUE THREAD

**Issue by andrestoga** [ysshao/LLVM-Tracer#10]
Hi Sophia, 

This is not an issue. I just want to ask you for help in understanding your code and see if it is possible to modify it to do a dynamic fault injection since you are doing a dynamic trace. I checked the full_trace.cpp source code and I saw that there is a function named "createCallForParameterLine". I wonder if in that function I can modify the register of a particular instruction and inject a wrong value? If so, could you give me a hint on how I can accomplish that? 

Best,

**Comment by ysshao** [comment]
hi @andrestoga , I think it's definitely doable. I would recommend you to check out the LLFI project to see how they get the fault injection done. You can find the project here:

https://github.com/DependableSystemsLab/LLFI

**Comment by xyzsam** [comment]
Closing due to lack of discussion.
