### ISSUE TITLE
-fulltrace is not supported by opt

### ISSUE THREAD

**Issue by z-a-f** [ysshao/LLVM-Tracer#13]
opt from LLVM 3.4 doesn't support `-fulltrace` argument

**Comment by ysshao** [comment]
hi @zafartahirov , you need to load the full_trace.so to have opt take the -fulltrace argument like this:

opt -S -load=$TRACER_HOME/full-trace/full_trace.so -fulltrace triad.llvm -o triad-opt.llvm

let me know how it goes.

**Comment by z-a-f** [comment]
So far I couldn't get the `opt ... -fulltrace` to work on llvm 3.4 - it works on 3.5 fine. I think I have some problem with compilation using mixed versions. I will make an ISO with both 34 and 35 versions, will try to make sure it works for both - will ping back after that

**Comment by xyzsam** [comment]
Closing due to lack of discussion.
