### ISSUE TITLE
Detailed documentation request

### ISSUE THREAD

**Issue by z-a-f** [ysshao/LLVM-Tracer#14]
I think it would be very useful if there was detailed documentation for general users and for developers. Poking through the code to figure out the reasons behind every method is a little  painful :smiling_imp:

**Comment by xyzsam** [comment]
Yes, I agree that documentation is lacking, but don't expect it to come all at once - we have many other commitments to attend to as well. We'll try to add more docs from time to time.

**Comment by xyzsam** [comment]
For those who were interested: I just completed a major refactor of LLVM-Tracer, which should make the code much more understandable, and lots of documentation has been added.
