### ISSUE TITLE
error in cmake ..

### ISSUE THREAD

**Issue by MasoomehJasemi** [ysshao/LLVM-Tracer#17]
hi 
when i run cmake i faced with below error 
masi@orca:~/LLVM-Tracer/build$ cmake ..
-- use LLVM_ROOT : usr/include/llvm-3.4/llvm
-- find LLVM-Config : /usr/bin/llvm-config-3.4
-- LLVM version : 3.4
-- LLVM_LINK found : /usr/bin/llvm-link-3.4
-- LLVM_OPT found : /usr/bin/opt-3.4
-- LLVM_LLC found : /usr/bin/llc-3.4
-- LLVM_COMPILER found : /usr/bin/clang
-- Could NOT find Curses (missing:  CURSES_LIBRARY CURSES_INCLUDE_PATH)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CURSES_CURSES_LIBRARY (ADVANCED)
    linked by target "get-labeled-stmts" in directory /home/masi/LLVM-Tracer/ast-pass

-- Configuring incomplete, errors occurred!
See also "/home/masi/LLVM-Tracer/build/CMakeFiles/CMakeOutput.log".

can u help me to solve it?
tnx

**Comment by xyzsam** [comment]
You need to install the curses library. On Ubuntu: `sudo apt-get install libncurses-dev`

**Comment by MasoomehJasemi** [comment]
Tnx a lot for your response, i solved it.
