### ISSUE TITLE
make not working

### ISSUE THREAD

**Issue by amirtaherin** [ysshao/LLVM-Tracer#25]
I run the cmake, after that when I tried the make command, I received the following error:

[  8%] Built target full_trace
[ 33%] Built target trace_logger
[ 33%] Built target PROFILE_FUNC
Scanning dependencies of target get-labeled-stmts
[ 41%] Building CXX object ast-pass/CMakeFiles/get-labeled-stmts.dir/GetLabeledStmts.cpp.o
/home/amir/aladdin/LLVM-Tracer/ast-pass/GetLabeledStmts.cpp:24:27: fatal error: clang/AST/AST.h: No such file or directory
 #include "clang/AST/AST.h"
                           ^
compilation terminated.
make[2]: *** [ast-pass/CMakeFiles/get-labeled-stmts.dir/GetLabeledStmts.cpp.o] Error 1
make[1]: *** [ast-pass/CMakeFiles/get-labeled-stmts.dir/all] Error 2
make: *** [all] Error 2

how can I solve this issue?
I'm using llvm-clang 3.4 and my gcc and g++ are 4.8
Thanks!

**Comment by rgly** [comment]
I would recommend you to test it on the official docker image.
hub.docker.io/xyzsam/gem5-aladdin

Or you might want to show the verbose logging by `make VERBOSE=1`, so that I can get the detailed gcc arguments.

**Comment by amirtaherin** [comment]
Thanks for your prompt reply!
I make with VERBOSE=1, and the following is the result:

/usr/bin/cmake -H/home/amir/aladdin/LLVM-Tracer -B/home/amir/aladdin/LLVM-Tracer/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/amir/aladdin/LLVM-Tracer/build/CMakeFiles /home/amir/aladdin/LLVM-Tracer/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/home/amir/aladdin/LLVM-Tracer/build'
make -f full-trace/CMakeFiles/full_trace.dir/build.make full-trace/CMakeFiles/full_trace.dir/depend
make[2]: Entering directory `/home/amir/aladdin/LLVM-Tracer/build'
cd /home/amir/aladdin/LLVM-Tracer/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/amir/aladdin/LLVM-Tracer /home/amir/aladdin/LLVM-Tracer/full-trace /home/amir/aladdin/LLVM-Tracer/build /home/amir/aladdin/LLVM-Tracer/build/full-trace /home/amir/aladdin/LLVM-Tracer/build/full-trace/CMakeFiles/full_trace.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/amir/aladdin/LLVM-Tracer/build'
make -f full-trace/CMakeFiles/full_trace.dir/build.make full-trace/CMakeFiles/full_trace.dir/build
make[2]: Entering directory `/home/amir/aladdin/LLVM-Tracer/build'
make[2]: Nothing to be done for `full-trace/CMakeFiles/full_trace.dir/build'.
make[2]: Leaving directory `/home/amir/aladdin/LLVM-Tracer/build'
/usr/bin/cmake -E cmake_progress_report /home/amir/aladdin/LLVM-Tracer/build/CMakeFiles  8
[  8%] Built target full_trace
make -f profile-func/CMakeFiles/trace_logger.dir/build.make profile-func/CMakeFiles/trace_logger.dir/depend
make[2]: Entering directory `/home/amir/aladdin/LLVM-Tracer/build'
cd /home/amir/aladdin/LLVM-Tracer/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/amir/aladdin/LLVM-Tracer /home/amir/aladdin/LLVM-Tracer/profile-func /home/amir/aladdin/LLVM-Tracer/build /home/amir/aladdin/LLVM-Tracer/build/profile-func /home/amir/aladdin/LLVM-Tracer/build/profile-func/CMakeFiles/trace_logger.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/amir/aladdin/LLVM-Tracer/build'
make -f profile-func/CMakeFiles/trace_logger.dir/build.make profile-func/CMakeFiles/trace_logger.dir/build
make[2]: Entering directory `/home/amir/aladdin/LLVM-Tracer/build'
make[2]: Nothing to be done for `profile-func/CMakeFiles/trace_logger.dir/build'.
make[2]: Leaving directory `/home/amir/aladdin/LLVM-Tracer/build'
/usr/bin/cmake -E cmake_progress_report /home/amir/aladdin/LLVM-Tracer/build/CMakeFiles  10 11 12
[ 33%] Built target trace_logger
make -f profile-func/CMakeFiles/PROFILE_FUNC.dir/build.make profile-func/CMakeFiles/PROFILE_FUNC.dir/depend
make[2]: Entering directory `/home/amir/aladdin/LLVM-Tracer/build'
cd /home/amir/aladdin/LLVM-Tracer/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/amir/aladdin/LLVM-Tracer /home/amir/aladdin/LLVM-Tracer/profile-func /home/amir/aladdin/LLVM-Tracer/build /home/amir/aladdin/LLVM-Tracer/build/profile-func /home/amir/aladdin/LLVM-Tracer/build/profile-func/CMakeFiles/PROFILE_FUNC.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/amir/aladdin/LLVM-Tracer/build'
make -f profile-func/CMakeFiles/PROFILE_FUNC.dir/build.make profile-func/CMakeFiles/PROFILE_FUNC.dir/build
make[2]: Entering directory `/home/amir/aladdin/LLVM-Tracer/build'
make[2]: Nothing to be done for `profile-func/CMakeFiles/PROFILE_FUNC.dir/build'.
make[2]: Leaving directory `/home/amir/aladdin/LLVM-Tracer/build'
/usr/bin/cmake -E cmake_progress_report /home/amir/aladdin/LLVM-Tracer/build/CMakeFiles 
[ 33%] Built target PROFILE_FUNC
make -f ast-pass/CMakeFiles/get-labeled-stmts.dir/build.make ast-pass/CMakeFiles/get-labeled-stmts.dir/depend
make[2]: Entering directory `/home/amir/aladdin/LLVM-Tracer/build'
cd /home/amir/aladdin/LLVM-Tracer/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/amir/aladdin/LLVM-Tracer /home/amir/aladdin/LLVM-Tracer/ast-pass /home/amir/aladdin/LLVM-Tracer/build /home/amir/aladdin/LLVM-Tracer/build/ast-pass /home/amir/aladdin/LLVM-Tracer/build/ast-pass/CMakeFiles/get-labeled-stmts.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/amir/aladdin/LLVM-Tracer/build'
make -f ast-pass/CMakeFiles/get-labeled-stmts.dir/build.make ast-pass/CMakeFiles/get-labeled-stmts.dir/build
make[2]: Entering directory `/home/amir/aladdin/LLVM-Tracer/build'
/usr/bin/cmake -E cmake_progress_report /home/amir/aladdin/LLVM-Tracer/build/CMakeFiles 9
[ 41%] Building CXX object ast-pass/CMakeFiles/get-labeled-stmts.dir/GetLabeledStmts.cpp.o
cd /home/amir/aladdin/LLVM-Tracer/build/ast-pass && g++   -DLLVM_VERSION=34 -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -Wall -W -Wno-unused-parameter -Wwrite-strings -pedantic -Wno-long-long -std=c++11 -fno-rtti -std=c++11 -O3 -I/usr/lib/llvm-3.4/include -I/usr/bin/include    -o CMakeFiles/get-labeled-stmts.dir/GetLabeledStmts.cpp.o -c /home/amir/aladdin/LLVM-Tracer/ast-pass/GetLabeledStmts.cpp
/home/amir/aladdin/LLVM-Tracer/ast-pass/GetLabeledStmts.cpp:24:27: fatal error: clang/AST/AST.h: No such file or directory
 #include "clang/AST/AST.h"
                           ^
compilation terminated.
make[2]: *** [ast-pass/CMakeFiles/get-labeled-stmts.dir/GetLabeledStmts.cpp.o] Error 1
make[2]: Leaving directory `/home/amir/aladdin/LLVM-Tracer/build'
make[1]: *** [ast-pass/CMakeFiles/get-labeled-stmts.dir/all] Error 2
make[1]: Leaving directory `/home/amir/aladdin/LLVM-Tracer/build'
make: *** [all] Error 2


can you please tell me how to solve this issue?

**Comment by rgly** [comment]
I guess the  problem is that you didn't install clang properly.
please check whether there's any `clang` directory under `/usr/lib/llvm-3.4/include`.
If not, please install clang with llvm from source code,
or in Ubuntu, apt install something like `libclang-dev`.
