### ISSUE TITLE
Undefined reference to clang::tooling::ClangTool::ClangTool

### ISSUE THREAD

**Issue by tamimcse** [ysshao/LLVM-Tracer#27]
I was getting linker error "undefined reference to clang::tooling::ClangTool::ClangTool.." on Ubuntu. I had to install libedit-dev to get it working. Probably it would be a good idea to add it to README.

**Comment by xyzsam** [comment]
I'm unsure how `libedit-dev` would make a difference here. It seems to me like the order of libraries would be more relevant, as suggested by the accepted answer here: https://askubuntu.com/questions/732326/undefined-references-compiling-clang-tutorial-on-14-04-2

@rgly implemented the CMake scripts so I will defer any future patches on library ordering to him.

**Comment by jiapei100** [comment]
@tamimcse 

Same here, Ubuntu 22.04.3, even with **libedit-dev** installed... Still buggy.
