### ISSUE TITLE
error during make

### ISSUE THREAD

**Issue by bwyogatama** [ysshao/LLVM-Tracer#28]
I had this error during make, can you help me figure out the problem??

[ 14%] Built target full_trace
[ 35%] Built target trace_logger
[ 35%] Built target PROFILE_FUNC
[ 42%] Linking CXX executable get-labeled-stmts
CMakeFiles/get-labeled-stmts.dir/GetLabeledStmts.cpp.o: In function `main':
GetLabeledStmts.cpp:(.text.startup+0x80): undefined reference to `clang::tooling::ClangTool::ClangTool(clang::tooling::CompilationDatabase const&, llvm::ArrayRef<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >)'
collect2: error: ld returned 1 exit status
ast-pass/CMakeFiles/get-labeled-stmts.dir/build.make:96: recipe for target 'ast-pass/get-labeled-stmts' failed
make[2]: *** [ast-pass/get-labeled-stmts] Error 1
CMakeFiles/Makefile2:228: recipe for target 'ast-pass/CMakeFiles/get-labeled-stmts.dir/all' failed
make[1]: *** [ast-pass/CMakeFiles/get-labeled-stmts.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

Thank you!

**Comment by rgly** [comment]
Issue https://github.com/ysshao/LLVM-Tracer/issues/27 and issue https://github.com/ysshao/LLVM-Tracer/issues/25 might help you.
