### ISSUE TITLE
"/bin/sh: 1: : Permission denied" when run "make"

### ISSUE THREAD

**Issue by hcyang11** [ysshao/LLVM-Tracer#29]
Hi. How to solve this when I run make under /LLVM-Trace/build after "cmake ..".
Thanks!

mca@ubuntu740:~/LLVM-Tracer/build$ make VERBOSE=1
/usr/bin/cmake -H/home/mca/LLVM-Tracer -B/home/mca/LLVM-Tracer/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/mca/LLVM-Tracer/build/CMakeFiles /home/mca/LLVM-Tracer/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/mca/LLVM-Tracer/build'
make -f full-trace/CMakeFiles/full_trace.dir/build.make full-trace/CMakeFiles/full_trace.dir/depend
make[2]: Entering directory '/home/mca/LLVM-Tracer/build'
cd /home/mca/LLVM-Tracer/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/mca/LLVM-Tracer /home/mca/LLVM-Tracer/full-trace /home/mca/LLVM-Tracer/build /home/mca/LLVM-Tracer/build/full-trace /home/mca/LLVM-Tracer/build/full-trace/CMakeFiles/full_trace.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/mca/LLVM-Tracer/build'
make -f full-trace/CMakeFiles/full_trace.dir/build.make full-trace/CMakeFiles/full_trace.dir/build
make[2]: Entering directory '/home/mca/LLVM-Tracer/build'
[  6%] Building CXX object full-trace/CMakeFiles/full_trace.dir/full_trace.cpp.o
cd /home/mca/LLVM-Tracer/build/full-trace && ""   -DLLVM_VERSION=34 -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -Dfull_trace_EXPORTS -I/home/mca/clang+llvm-3.4-x86_64-linux-gnu-ubuntu-13.10/include  -Wall -W -Wno-unused-parameter -Wwrite-strings -pedantic -Wno-long-long -std=c++11 -fno-rtti -O3 -fPIC   -o CMakeFiles/full_trace.dir/full_trace.cpp.o -c /home/mca/LLVM-Tracer/full-trace/full_trace.cpp
/bin/sh: 1: : Permission denied
full-trace/CMakeFiles/full_trace.dir/build.make:62: recipe for target 'full-trace/CMakeFiles/full_trace.dir/full_trace.cpp.o' failed
make[2]: *** [full-trace/CMakeFiles/full_trace.dir/full_trace.cpp.o] Error 127
make[2]: Leaving directory '/home/mca/LLVM-Tracer/build'
CMakeFiles/Makefile2:85: recipe for target 'full-trace/CMakeFiles/full_trace.dir/all' failed
make[1]: *** [full-trace/CMakeFiles/full_trace.dir/all] Error 2
make[1]: Leaving directory '/home/mca/LLVM-Tracer/build'
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by xyzsam** [comment]
What OS/environment are you trying to build this on? It doesn't look like you are using the Docker image. 

`/bin/sh: 1: : Permission denied` is strange - apparently it's not letting you execute shell scripts?

**Comment by xyzsam** [comment]
Closing this issue since it has been silent for some time. If this is still an issue, feel free to re-open.
