### ISSUE TITLE
Segmentation Fault on all programs.

### ISSUE THREAD

**Issue by dilinade** [ysshao/LLVM-Tracer#30]
When trying to execute any program it gives out this error.
```
Starting to log at inst = 0.
Segmentation fault (core dumped)


```
It also generates a corrupted **dynamic_trace.gz** file.

**Comment by xyzsam** [comment]
I'll need more information to help you. What are you trying to build? What is your build environment? Are you using docker? How did you install/compile LLVM?

**Comment by dilinade** [comment]
I'm trying to run the example triad program and my environment comprises of LLVM 3.4 , CMake version 3.9.6 with gcc 4.7.3 on Ubuntu 12.04 32bit.
I didn't use docker, compiled it from the source itself.

**Comment by xyzsam** [comment]
Following up on old issues here - if you didn't use docker, then that's what I suggest you start with. I have seen this error occasionally from other users and it usually boils down to some obscure environment difference.

If you've resolved this issue already, then just close the issue. Thanks!
