### ISSUE TITLE
Project doesn't compile with LLVM 10

### ISSUE THREAD

**Issue by Michael137** [ysshao/LLVM-Tracer#31]
It's a large jump from the last version it supported so just putting this here while I am trying to fix things incrementally. If anyone has a newer port this would be greatly appreciated

**Comment by xyzsam** [comment]
We have internally ported the project to LLVM 6. We are hoping to release it soon for beta testing. But I would not expect a port to LLVM 10 from us in the near future.

**Comment by Michael137** [comment]
Ah that would be great. I'm probably going to need it within few days for a class project so I resorted to not using the tool atm. But I'm looking forward to the release for use in subsequent work

**Comment by xyzsam** [comment]
Hi - I have just pushed a major update to LLVM-Tracer, supporting LLVM-6, to the [llvm-6.0](https://github.com/ysshao/LLVM-Tracer/tree/llvm-6.0) branch. If you have a chance to try it out, we would be glad to hear your feedback.
