### ISSUE TITLE
Dynamic Trace File Error

### ISSUE THREAD

**Issue by SumantSakhalkar** [ysshao/LLVM-Tracer#32]
I have observed that when I write the inputs (Main function) to the kernel in a different C file the dynamic trace file doesn't consider it. The Dynamic Trace file would just show me the labelmap and not any traces to the kernel. Am I missing something??
I am working on a docker.

**Comment by xyzsam** [comment]
If you changed the name of the kernel, you also need to change the value of
the WORKLOAD environment variable and rebuild the instrumented binary.

Sam Xi
Google Inc., Software Engineer
http://www.samxi.org

**Comment by SumantSakhalkar** [comment]
I am working on the fft kernel in MachSuite Benchmark. The main function is contained in fft_test.c file and the kernel is named fft1d_512 which lies in fft.c. I have set the WORKLOAD variable to fft1D_512 and tried to rebuild the instrumented binary, but had the same issues. No traces in the dynamic_trace.gz just the labelmap.

**Comment by xyzsam** [comment]
Following up on old issues. Is this resolved?
