### ISSUE TITLE
typo in README.md

### ISSUE THREAD

**Issue by Geof23** [ysshao/LLVM-Tracer#4]
llvm-link -o full.llvm triad-opt.llvm $TRACER_HOME/profile-func/tracer_logger.llvm

should be:

llvm-link -o full.llvm triad-opt.llvm $TRACER_HOME/profile-func/trace_logger.llvm

**Comment by ysshao** [comment]
Good catch! Fixed in the latest commit.

**Comment by Geof23** [comment]
Thanks Sophia
