### ISSUE TITLE
How to generate LLVM6.0 trace of the main function(C++)?

### ISSUE THREAD

**Issue by rem1A** [ysshao/LLVM-Tracer#45]
As I see the example in the playground, the WORKLOAD is top_level, which is a function defined outside the main(), and it run successfully. But when I try to change the WORKLOAD to main, it reports error like this:

test-instrumented: /workspace/LLVM-Tracer/profile-func/trace_logger.cpp:132: logging_status log_or_not(bool, bool, int, char *): Assertion `false && "Returning from within a toplevel function before it was called!"' failed.
Aborted (core dumped)

If I want to generate LLVM trace of the whole main function, what should I do?Or is it possible to make it in a C++ program using LLVM-Tracer 6.0?Did I missed any details?

Thank you very much

Kind regards

**Comment by xyzsam** [comment]
You can't trace `main` directly, but you can put all your code into a `runMain` function which you then trace.

**Comment by rem1A** [comment]
THANKS A LOT !!! I will try
