### ISSUE TITLE
Program example: /usr/bin/ld: cannot find -lm collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by andrestoga** [ysshao/LLVM-Tracer#8]
Hi Sophia,

I tried to run the example using the python file but I got the following error:

/usr/bin/ld: cannot find -lm
collect2: error: ld returned 1 exit status

I believe it is something related to the missing library libm. Is that correct?

Best,

**Comment by ysshao** [comment]
Yes, it's correct. You may find the second answer to this post useful for your case:

http://stackoverflow.com/questions/16710047/usr-bin-ld-cannot-find-lnameofthelibrary

Let me know how it goes.

Thanks,
Sophia

**Comment by andrestoga** [comment]
Thanks Sophia! That was very useful! I worked out for the libm library but then I had the problem of another missing library: libz. In this one I had a lot of trouble because the ones I have installed seem to have some problems. So, I had to use a third party library (lampp) for the libz. It worked.

I really appreciate your help!

Kind regards,

**Comment by ysshao** [comment]
Good to hear =D
